#!/bin/bash
set -eu -o pipefail

#
# Build the Docker image
#
# Usage:
#   <<
#     $ ./build
#   <<
#
# Requires:
#	- docker
#
# References:
#   - 'firebase-tools' releases
#     -> https://github.com/firebase/firebase-tools/releases

# Note: Keep the variable name, read from 'push-to-gcr'.
#_VERSION=9.17.0
_VERSION=10.0.1

_IMAGE_NAME=firebase-ci-builder

# Note: '-nodeXY-npmZ' is NOT connected with what the base image in 'Dockerfile' provides. MAINTAIN MANUALLY!!!
#_TAG=${_VERSION}-node16-npm7
_TAG=${_VERSION}-node16-npm8

docker build --pull --build-arg FIREBASE_VERSION=${_VERSION} . -t ${_IMAGE_NAME}:${_TAG}
